version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "03:00"
      timezone: "Asia/Ho_Chi_Minh"
    open-pull-requests-limit: 10
  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "daily"
      time: "03:00"
      timezone: "Asia/Ho_Chi_Minh"
    open-pull-requests-limit: 10
