---
name: ProfanityFilter
version: 1.0.0
main: NhanAZ\ProfanityFilter\ProfanityFilter
api: 4.0.0
src-namespace-prefix: NhanAZ\ProfanityFilter

website: github.com/nhanaz-pm-pl/ProfanityFilter
description: Powerful Profanity Filter Plugin For PocketMine-MP Servers
author: NhanAZ
extensions:
  core: ">=8.0"

permissions:
  profanityfilter.bypass:
    description: "Bypass plugin's filter!"
    default: op
...
